print('CHALLENGE 04')
var = input('Digite um valor qualquer:')
print('Sua variável é do tipo:', type(var))
print('SUa váriável é um espaço?', var.isspace())
print('Sua variável é alfanumérica?', var.isalnum())
print('Sua variável é um número?', var.isnumeric())
print('Sua variável é imrpimível?', var.isprintable())
print('Sua variável é letra?', var.isalpha())
print('Sua variável está capitalizada(com letras maiúsculas)?', var.istitle())
