print('CHALLENGE 10')
print('='*20, 'Conversor de moedas', '='*20)
carteira = float(input('Quantos reais você tem? R$'))
print('-'*60)
dollar = (carteira / 4.94)
euro = (carteira / 5.88)
canadiandollar = (carteira / 3.98)
libraesterlina = (carteira / 6.84)
print(f'Você pode obter as seguintes moedas com o seu dinheiro atual: R${carteira:.2f}!')
print(f'Dólar Estadunidense: US${dollar:.2f}')
print(f'Euro: €{euro:.2f}')
print(f'Dólar Canadense: CAD${canadiandollar:.2f}')
print(f'Libra esterlina: £{libraesterlina:.2f}')
print('-'*60)